# fly.toml app configuration file generated for cap-hill-rust on 2023-10-08T18:39:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cap-hill-rust"
primary_region = "sea"

[build]
  image = "cap-hill-rust:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
